app/models/navigation.py
from sqlalchemy import event, orm

from app import db, get_locale
from app.models.base_model import BaseEntity


class NavigationEntry(db.Model, BaseEntity):
    __tablename__ = 'nagivation_entry'

    prints = ('id', 'parent_id', 'nl_title', 'en_title', 'url', 'external')

    parent_id = db.Column(db.Integer, db.ForeignKey('nagivation_entry.id'))
    page_id = db.Column(db.Integer, db.ForeignKey('page.id'))
    nl_title = db.Column(db.String(256))
    en_title = db.Column(db.String(256))
    url = db.Column(db.String(256))
    external = db.Column(db.Boolean)
    activity_list = db.Column(db.Boolean)
    position = db.Column(db.Integer)
    order_children_alphabetically = db.Column(db.Boolean(), default=False,
                                              nullable=False)

    parent = db.relationship(
        'NavigationEntry', remote_side='NavigationEntry.id',
        primaryjoin=('NavigationEntry.parent_id==NavigationEntry.id'),
        backref=db.backref('children', lazy='dynamic',
                           order_by='NavigationEntry.position'))

    page = db.relationship('Page', backref=db.backref('navigation_entry',
                                                      lazy='joined'),
                           lazy='joined')

    @orm.reconstructor
    def orm_init(self):
        self.children_fast = []

    def __init__(self, parent, nl_title, en_title, url, page_id, external,
                 activity_list, position, subtitle=None):
        if parent:
            self.parent_id = parent.id

        self.title = None
        self.nl_title = nl_title
        self.en_title = en_title
        self.url = url
        self.page_id = page_id
        self.external = external
        self.activity_list = activity_list
        self.position = position
        self.subtitle = subtitle
        self.children_fast = []
        set_navigation_entry_locale(self, None)

    def get_children(self):
        if self.order_children_alphabetically:
            return sorted(self.children_fast, key=lambda x: x.title)
        else:
            return self.children_fast

    @property
    def href(self):
        if self.external and self.url:
            return 'https://' + self.url
        else:
            return self.url if self.url else '/' + self.page.path


@event.listens_for(NavigationEntry, 'load')
def set_navigation_entry_locale(nav_entry, context):
    """
    Fill model content according to language.

    This function is called after an NavigationEntry model is filled with data
    from the database, but before is used in all other code.

    Use the locale of the current user/client to determine which language to
    display on the whole website. If the users locale is unavailable, select
    the alternative language, suffixing the title of the activity with the
    displayed language.
    """
    locale = get_locale()
    if locale == 'nl' and nav_entry.nl_title:
        nav_entry.title = nav_entry.nl_title
    elif locale == 'en' and nav_entry.en_title:
        nav_entry.title = nav_entry.en_title
    elif nav_entry.nl_title:
        nav_entry.title = nav_entry.nl_title
    elif nav_entry.en_title:
        nav_entry.title = nav_entry.en_title
    else:
        nav_entry.title = 'N/A'

app/forms/navigation.py
from flask_babel import lazy_gettext as _
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, SelectField
from wtforms.validators import InputRequired, ValidationError


class NavigationEntryForm(FlaskForm):
    nl_title = StringField(_('Dutch title'), validators=[
        InputRequired(_('Dutch title') + " " + ('is required'))
    ])
    en_title = StringField(_('English title'), validators=[
        InputRequired(_('English title') + ' ' + ('is required'))
    ])
    url = StringField('URL')
    page_id = SelectField(_('Page'), coerce=int)
    # parent_id = StringField(_('List'))
    external = BooleanField(_('External link'), default=False)
    activity_list = BooleanField(_('List of activities'), default=False)
    order_children_alphabetically = BooleanField(
        _("Order children alphabetically"), default=False)

    def validate_url(self, field):
        if self.page_id.data == -1 and not field.data.strip():
            raise ValidationError('URL ' + _('is required'))

app/views/navigation.py
import json
import re
from flask import Blueprint, render_template, abort, request, flash, \
    redirect, url_for
from flask_babel import _
from flask_login import current_user

from app import db
from app.decorators import require_role
from app.forms import init_form
from app.forms.navigation import NavigationEntryForm
from app.models.navigation import NavigationEntry
from app.models.page import Page
from app.roles import Roles
from app.service import role_service, page_service
from app.utils.forms import flash_form_errors
from app.utils.navigation import NavigationAPI
from app.utils.resource import get_all_routes

blueprint = Blueprint('navigation', __name__, url_prefix='/navigation')


@blueprint.route('/')
@require_role(Roles.NAVIGATION_WRITE)
def view():
    entries = NavigationAPI.get_root_entries()
    can_write = role_service.user_has_role(current_user,
                                           Roles.NAVIGATION_WRITE)
    return render_template('navigation/view.htm', nav_entries=entries,
                           can_write=can_write)


@blueprint.route('/create/', methods=['GET', 'POST'])
@blueprint.route('/create/<int:parent_id>/', methods=['GET', 'POST'])
@blueprint.route('/edit/<int:entry_id>/', methods=['GET', 'POST'])
@require_role(Roles.NAVIGATION_WRITE)
def edit(entry_id=None, parent_id=None):
    entry = NavigationEntry.query.get_or_404(entry_id) if entry_id else None
    form = init_form(NavigationEntryForm, obj=entry)
    form.page_id.choices = [(-1, '-- {} --'.format(_('Custom URL')))] + \
        db.session.query(Page.id, Page.path).all()

    parent = NavigationEntry.query.get(parent_id) if parent_id else None
    if parent_id and not parent:
        flash(_('Cannot find parent navigation entry.'), 'danger')
        return redirect(url_for('navigation.view'))

    if form.validate_on_submit():
        url = None
        if form.page_id.data == -1:
            url = form.url.data
            if not re.compile('^/').match(url):
                url = '/' + url

        page_id = None if form.page_id.data == -1 else form.page_id.data

        if entry:
            entry.nl_title = form.nl_title.data
            entry.en_title = form.en_title.data
            entry.url = url
            entry.page_id = page_id
            entry.external = form.external.data
            entry.activity_list = form.activity_list.data
            entry.order_children_alphabetically = \
                form.order_children_alphabetically.data
        else:
            last_entry = NavigationEntry.query.filter_by(parent_id=None) \
                .order_by(NavigationEntry.position.desc()).first()

            # If there is no parent position the new entry at the end of the
            # top level entry.
            position = (last_entry.position + 1) if last_entry else 0

            entry = NavigationEntry(parent, form.nl_title.data,
                                    form.en_title.data, url, page_id,
                                    form.external.data,
                                    form.activity_list.data, position)

        db.session.add(entry)
        db.session.commit()
        flash(_('The navigation entry has been saved.'), 'success')

        if not page_id and not form.external.data:
            # Check if the page exists, if not redirect to create it
            path = form.url.data.lstrip('/')
            page = page_service.get_page_by_path(path)
            if url.rstrip('/') in get_all_routes():
                return redirect(url_for('navigation.view'))
            if not page and form.url.data != '/':
                flash(_('The link refers to a page that does not exist, please'
                        'create the page!'), 'warning')
                return redirect(url_for('page.edit_page', path=path))

        return redirect(url_for('navigation.view'))

    else:
        flash_form_errors(form)

    parents = NavigationEntry.query.filter_by(parent_id=None)
    if entry:
        parents = parents.filter(NavigationEntry.id != entry.id)

    return render_template('navigation/edit.htm', entry=entry, form=form,
                           parents=parents.all())


@blueprint.route('/delete/<int:entry_id>/', methods=['POST'])
@blueprint.route('/delete/<int:entry_id>/<int:inc_page>', methods=['POST'])
@require_role(Roles.NAVIGATION_WRITE)
def delete(entry_id, inc_page=0):
    if inc_page and not role_service.user_has_role(current_user,
                                                   Roles.PAGE_WRITE):
        flash(_('You do not have rights to remove pages'))
        return abort(403)

    entry = db.session.query(NavigationEntry).filter_by(id=entry_id).first()
    if not entry:
        abort(404)

    if not entry.parent:
        if entry.children.count() > 0:
            flash('Deze item heeft nog subitems.', 'danger')
            return redirect(url_for('navigation.edit', entry_id=entry.id))

    if inc_page:
        if entry.external or entry.activity_list:
            flash('Deze item verwijst niet naar een pagina op deze website.',
                  'danger')
        else:
            if (entry.url is None or page_service.delete_page_by_path(
                    entry.url.lstrip('/'))):
                flash('De pagina is verwijderd.', 'success')
            else:
                flash('De te verwijderen pagina kon niet worden gevonden.',
                      'danger')

    db.session.delete(entry)
    db.session.commit()

    flash('De navigatie-item is verwijderd.', 'success')

    return redirect(url_for('navigation.view'))


@blueprint.route('/navigation/reorder', methods=['POST'])
@require_role(Roles.NAVIGATION_WRITE)
def reorder():
    entries = json.loads(request.form['entries'])
    NavigationAPI.order(entries, None)

    return ""

app/templates/navigation/edit.htm
{% from "macros/form.htm" import render_form, render_submit %}

{% extends "content.htm" %}

{% block content %}

    <form action="" method="post" name="edit_navigation_entry">
        <fieldset>
            <legend>
                {% if entry %}
                    {{_('Create')}}
                {% else %}
                    {{_('Edit')}}
                {% endif %}
                {{_('Navigation entry')}}
            </legend>

            {{ form.csrf_token }}

            {{ render_form(form) }}

            <input type="hidden" name="parent_id"
                   value="{{ request.args.get("parent_id") }}">

        </fieldset>
    </form>
    <div class="row">
    {% if entry and entry.children.count() == 0 %}
        <div class="col-md-2">
            <form action="{{ url_for('navigation.delete', entry_id=entry.id) }}"
                  method="post">
                {{ render_submit(_('Delete'), class='btn-danger') }}
            </form>
        </div>
        {% if not entry.external and not entry.activity_list %}
            <div class="col-md-10">
                <form action="{{ url_for('navigation.delete', entry_id=entry.id, inc_page=1) }}" method="post">
                    {{ render_submit(_('Delete menu item and pagina'), class='btn-danger') }}
                </form>
            </div>
        {% endif %}
    {% endif %}
    </div>

    <script>
        function updateURLBoxState(pageID) {
            if (pageID.val() != -1)
                $('#url').prop('disabled', true).val('');
            else
                $('#url').prop('disabled', false);
        }

        $('#page_id').change(function() {
            updateURLBoxState($(this));
        });
        $(function() {
            updateURLBoxState($('#page_id'));
        });
    </script>
{% endblock %}

app/templates/navigation/entry_list.htm
{% macro render_entry_list(entry, can_write) %}
	<div class="nav_entry" data-entry-id="{{ entry.id }}">
			<span class="sortable_handler">
				<i class="glyphicon glyphicon-move"></i>
			</span>	
			{{ entry.title }}

		{% if can_write %}
			<a class="btn btn-success pull-right" href="{{ url_for('navigation.edit', parent_id=entry.id) }}">
				<i class="glyphicon glyphicon-plus"></i>
			</a>
			<a class="btn btn-success pull-right" style="margin-right: 5px;" href="{{ url_for('navigation.edit', entry_id=entry.id) }}">
				<i class="glyphicon glyphicon-pencil"></i>
			</a>			
			<a class="btn btn-success pull-right show_nav_entry" style="margin-right: 5px; display:none;" href="#">
				<i class="glyphicon glyphicon-eye-open"></i>
			</a>			
			<a class="btn btn-success pull-right hide_nav_entry" style="margin-right: 5px;" href="#">
				<i class="glyphicon glyphicon-eye-close"></i>
			</a>
		{% endif %}

		<div class="sortable">
			{% for child in entry.children %}
				{{ render_entry_list(child, can_write) }}
			{% endfor %}
		</div>
	</div>
{% endmacro %}

app/templates/navigation/sidenav.htm
<ul class="nav nav-stacked nav-tabs">
	{% if current_page.count('/') > 0 %}
	<li>
		<a href="{{ url_for('page.view_page', page_path='/'.join(current_page.split('/')[:-1])) }}"><i class="glyphicon glyphicon-chevron-left"></i> Go back</a>
	{% endif %}

	{% for sibbling in sibblings %}
		{% if sibbling.path == current_page %}
			<li class="active">
				<a href="">{{sibbling.title}}</a>
			</li>

			{% for child in children %}
				<li>
				<a href="{{ url_for('page.view_page', page_path=child.path) }}"><i class="glyphicon glyphicon-chevron-right"></i> {{child.title}}</a>
				</li>
			{% endfor %}
		{% else %}
			<li>
				<a href="{{ url_for('page.view_page', page_path=sibbling.path) }}">{{sibbling.title}}</a>
			</li>
		{% endif %}

	{% endfor %}
</ul>

app/templates/navigation/view.htm
{% from "navigation/entry_list.htm" import render_entry_list %}

{% extends "content.htm" %}

{% block includes %}
    <script>
        var reorder_url = '{{ url_for("navigation.reorder") }}';
        var flash_succes_msg = '{{ _("The order has been saved successfully")}}';
    </script>
    <script src="{{static_url("/static/js/navigation/view.js")}}"></script>
{% endblock %}

{% block content %}

    <a class="btn btn-success pull-left" href="{{ url_for('navigation.edit') }}" style="margin-bottom: 15px;">
        <i class="glyphicon glyphicon-plus"></i>{{_('New item')}}
    </a>
    {% if nav_entries %}
        <div id="outer" class="sortable col-md-6">
            {% for entry in nav_entries %}
                {{ render_entry_list(entry, can_write) }}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

app/templates/navigation/view_backtrack.htm
<p>
  {% for tracker in backtrack %}
    <a href="{{ tracker.href }}">{{ tracker.title }}</a>
      {% if tracker != backtrack[-1] %}
      <i class="glyphicon glyphicon-chevron-right"></i>
      {% endif %}
  {% endfor %}
</p>

app/templates/navigation/view_bar.htm
{% from "macros/form.htm" import render_field, render_checkbox, render_submit %}
{% from "macros/user.htm" import render_uvanetid_signin_button %}
    <header>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        {% if current_user.is_anonymous %}
                            <img class="visible-xs img-rounded" src="/static/img/user.png" alt="..." id="loginImageMobile" data-target="#bs-example-navbar-collapse-2" data-toggle="collapse">
                        {% else %}
                            <img class="visible-xs img-rounded" src="{{ UserAPI.avatar(current_user) }}" alt="..." id="loginImageMobile" data-target="#bs-example-navbar-collapse-2" data-toggle="collapse">
                        {% endif %}
                          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>

                        <a class="navbar-brand" href="/"><img src="/static/img/via.png" width="80"/></a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            {% for entry in bar_entries %}

                                {% set children = entry.activities if entry.activities else entry.get_children() %}
                                {% set children = NavigationAPI.remove_unauthorized(children) %}

                                <li class="{% if children %}dropdown{% endif %}">
                                    <a {% if children %}class="dropdown-toggle" {% endif %} {% if entry.external %}target="_blank"{% endif %}
                                    href="{{ entry.href }}">
                                        {{ entry.title }}
                                    </a>

                                    <ul class="dropdown-menu
                                        {% if entry.activities %}
                                            dropdown-menu-activity

                                        {% endif %}
                                        "
                                        >
                                        {% for child in children %}
                                        {% set grandChildren = child.get_children() if not entry.activities %}
                                        {% set grandChildren = NavigationAPI.remove_unauthorized(grandChildren) %}

                                             <li {% if grandChildren %} class="dropdown-submenu" {% endif %}>
                                                <a {% if child.external %}target="_blank"{% endif %} href="{{ child.href }}" {% if grandChildren %} class="dropdown-toggle" {% endif %} >
                                                {% if child.subtitle %}
                                                    <small class="pull-right"> {{ child.subtitle|truncate(40)  }}</small>
                                                {% endif %}
                                                {{ child.title }}
                                                {% if child.subtitle %}
                                                    <small class="invisible"> {{ child.subtitle|truncate(40)  }}</small>
                                                {% endif %}
                                                </a>
                                                <ul class="dropdown-menu">
                                                    {% for grandChild in grandChildren %}
                                                     <li><a href="{{ grandChild.href }}">
                                                        <span>{{ grandChild.title }}</span>
                                                    </li></a>
                                                    {% endfor %}
                                                </ul>
                                            </li>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endfor %}
                        </ul>

                        <div class="dropdown">
                        {% if current_user.is_anonymous %}
                         <a data-toggle="dropdown" href="#">
                            <img class="hidden-xs img-rounded" src="/static/img/user.png" alt="..." id="loginImage">
                          </a>
                          <div class="dropdown-menu" id="loginContainer">

                            {{ render_uvanetid_signin_button(_('Log in with UvA-net ID'), href=url_for('saml.login'), small=True) }}

                            <hr class="hr-small">

                            <form method="post" name="sign-in" id="sign-in-menu" action="{{ url_for('user.sign_in') }}">
                            {{ login_form.csrf_token }}
                            {{ render_field(login_form.email) }}
                            {{ render_field(login_form.password) }}

                            {{ render_submit('Log in') }}
                            <ul class='list-unstyled' id='dropmenu-list'>
                                <li><a href="{{ url_for('user.sign_up')}}">{{_('Register new user')}}</a></li>
                                <li><a href="{{ url_for('user.request_password')}}">{{_('Forgot password?')}}</a></li>
                            </ul>
                            </form>
                          </div>
                        {% else %}
                          <a data-toggle="dropdown" href="#">
                            <img class="hidden-xs img-rounded" src="{{ UserAPI.avatar(current_user) }}" alt="..." id="loginImage" >
                          </a>
                          <div class="dropdown-menu" id="loginContainer">
                            <img src="{{ UserAPI.avatar(current_user) }}" alt="..." id="userImage" class="img-rounded hidden-xs">
                            <div id="userInformation">
                                <h4 class="username">{{ current_user.name }}</h4>
                                <p>{{ current_user.email }}</p>
                                <p>
                                    <a href="{{ url_for('user.view_single_self') }}">{{ _("Show profile") }}</a>
                                </p>
                                <p>
                                    <a href="{{ url_for('user.change_password', user_id=current_user.id) }}">{{ _("Change password") }}</a>
                                </p>
                                {#<p>
                                    <a href="{{ url_for('oauth.list_clients') }}">{{ _("Connected applications") }}</a>
                                </p>#}
                            </div>
                            <div id="logoutButtonContainer">
                                <a href="{{ url_for('user.sign_out') }}">
                                    <button class="btn btn-primary fullWidth">{{ _("Log off") }}</button>
                                </a>
                            </div>
                          </div>
                           {% endif %}
                        </div>
                    </div><!-- /.navbar-collapse -->
                    <div class="collapse navbar-collapse loginForMobile" id="bs-example-navbar-collapse-2">

                        {% if current_user.is_anonymous %}
                            {{ render_uvanetid_signin_button(_('Log in with UvA-net ID'), href=url_for('saml.login'), small=True) }}

                            <hr class="hr-small">
                            <form method="post" name="sign-in" id="sign-in-menu-mobile" action="{{ url_for('user.sign_in') }}">
                            {{ login_form.csrf_token }}
                            {{ render_field(login_form.email) }}
                            {{ render_field(login_form.password) }}

                            {{ render_submit('Log in') }}
                            <ul class='list-unstyled' id='dropmenu-list'>
                                <li><a href="{{ url_for('user.sign_up')}}">{{_('Register account')}}</a></li>
                                <li><a href="{{ url_for('user.request_password')}}">{{_('Forgot password?')}}</a></li>
                            </ul>
                            </form>

                        {% else %}

                            <img src="{{ UserAPI.avatar(current_user) }}" alt="..." id="userImageMobile" class="img-rounded">
                            <div id="userInformationMobile">
                                <h4 class="username">{{ current_user.name }}</h4>
                                <p>{{ current_user.email }}</p>
                                <p>
                                    <a href="{{ url_for('user.view_single_self') }}">{{ _("Show profile") }}</a>
                                </p>
                                <p>
                                    <a href="{{ url_for('user.change_password', user_id=current_user.id) }}">{{ _("Change password") }}</a>
                                </p>
                                {#<p>
                                    <a href="{{ url_for('oauth.list_clients') }}">{{ _("Connected applications") }}</a>
                                </p>#}
                            </div>
                            <div id="logoutButtonContainerMobile">
                                <a href="{{ url_for('user.sign_out') }}">
                                    <button class="btn btn-primary fullWidth">{{ _("Log off") }}</button>
                                </a>
                            </div>

                       {% endif %}



                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </div>
        </div>
    </nav>
    </header>

app/templates/navigation/view_sidebar.htm
{% if current != None %}

<div class="col-sm-2 col-md-2 side-menu">
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
        	{% for i, page in enumerate(pages) %}
                <a {% if page.external %}target="_blank"{% endif %} href="{{ page.href }}">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                           {{ page.title }}
                        </h4>
                    </div>
                </a>
                {% set children = page.activities if page.activities else page.get_children() %}
				{% set children = NavigationAPI.remove_unauthorized(children) %}

				{% if children and page.id == current.id %}
                    <div id="{{i}}" class="panel-collapse">
                        {% for child in children %}
                        <a {% if child.external %}target="_blank"{% endif %} href="{{ child.href }}">
                            <div class="panel-heading sub-panel-heading">
                                <h4 class="panel-title sub-panel-title">
                                    {{ child.title }}
                                </h4>
                            </div>
                        </a>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

{% endif %}