app/models/file.py
from app import db
from app.models.base_model import BaseEntity
from app.enums import FileCategory
from sqlalchemy import UniqueConstraint


class File(db.Model, BaseEntity):
    """Contains the metadata of an uploaded file."""

    __tablename__ = 'file'

    hash = db.Column(db.String(200), nullable=False)
    extension = db.Column(db.String(20), nullable=False)

    category = db.Column(db.Enum(FileCategory, name='file_category'),
                         nullable=False)
    display_name = db.Column(db.String(200))

    @property
    def full_display_name(self):
        if not self.display_name:
            return None

        name = self.display_name
        if len(self.extension) > 0:
            name += "." + self.extension

        return name

    __table_args__ = (UniqueConstraint('display_name', 'extension'),)

app/forms/file.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField

from flask_babel import lazy_gettext as _


class FileForm(FlaskForm):
    file = FileField(_('File'), render_kw={'multiple': True})

app/views/file.py
"""Views for the file module."""
from flask import Blueprint, render_template, request, flash, \
    abort, redirect, url_for
from flask_login import current_user

from app.decorators import require_role
from app.forms.file import FileForm
from app.enums import FileCategory
from app.roles import Roles
from app.service import role_service, file_service

blueprint = Blueprint('file', __name__, url_prefix='/files')


@blueprint.route('/', methods=['GET'])
@blueprint.route('/<int:page_nr>/', methods=['GET'])
@require_role(Roles.FILE_READ)
def list(page_nr=1):
    """List all files that are not assigned to a page."""

    search = request.args.get('search', None)
    per_page = 30

    if search:
        files = file_service.search_files_in_uploads(search)[:per_page]
        files_paginated = None
    else:
        files_paginated = file_service.get_all_files_in_category(
            FileCategory.UPLOADS, page_nr, per_page)
        files = files_paginated.items

    form = FileForm()

    can_write = role_service.user_has_role(current_user, Roles.FILE_WRITE)

    return render_template('files/list.htm', files=files, form=form,
                           files_paginated=files_paginated, search=search,
                           can_write=can_write)


@blueprint.route('/', methods=['POST'])
@blueprint.route('/<int:page_nr>/', methods=['POST'])
@require_role(Roles.FILE_WRITE)
def upload(page_nr=1):
    """Upload a file."""
    new_files = []
    for new_file in request.files.getlist('file'):
        # File upload request, but no added files
        if new_file.filename == '':
            flash("No files selected", 'danger')
            return redirect(url_for('.list', page_nr=page_nr))

        f = file_service.add_file(FileCategory.UPLOADS, new_file,
                                  new_file.filename)
        new_files.append(f)

    files_paginated = file_service.get_all_files_in_category(
        FileCategory.UPLOADS, page_nr, 30)
    files = files_paginated.items

    form = FileForm()

    can_write = role_service.user_has_role(current_user, Roles.FILE_WRITE)

    return render_template('files/list.htm', files=files, form=form,
                           files_paginated=files_paginated, search=None,
                           new_files=new_files, can_write=can_write)


@blueprint.route('/content/<int:file_id>/<string:file_hash>/', methods=['GET'])
def content(file_id, file_hash):
    f = file_service.get_file_by_id(file_id)

    if f.category != FileCategory.UPLOADS or f.hash != file_hash:
        return abort(404)

    content = file_service.get_file_content(f)
    headers = file_service.get_file_content_headers(f)

    return content, headers

app/templates/files/list.htm
{% from "macros/pagination.htm" import render_pagination %}
{% from "macros/form.htm" import render_form %}

{% extends "base.htm" %}

{% block includes %}
{%- if new_files -%}
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/jquery.tooltipster/4.1.4/css/tooltipster.bundle.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/jquery.tooltipster/4.1.4/css/plugins/tooltipster/sideTip/themes/tooltipster-sideTip-borderless.min.css" />
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.tooltipster/4.1.4/js/tooltipster.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/clipboard.js/1.5.12/clipboard.min.js"></script>
    <script>
        $(document).ready(function() {
            //Initialize the 'Link copied' tooltip
            var options = {
                theme: 'tooltipster-borderless',
                trigger: 'custom',
                animation: 'fade',
                triggerClose: {
                    click: true,
                    mouseleave: true,
                    originClick: true,
                    scroll: true,
                    tap: true,
                    touchleave: true
                }
            };

            {% for index, _ in enumerate(new_files) %}
                $('#url-copy-btn-{{ index }}').tooltipster(options);

                var clipboard = new Clipboard('#url-copy-btn-{{ index }}');
                clipboard.on('success', function(e) {
                    $(e.trigger).tooltipster('open');
                    e.clearSelection();
                });
            {% endfor %}
        });
    </script>
{%- endif -%}
{% endblock %}

{% block page %}

{%- if can_write -%}
        {%- if new_files -%}
        <div class="panel panel-default">
            <div class="panel-heading">{{_('Uploaded files')}}</div>
            <div class="panel-body">
            {% for index, new_file in enumerate(new_files) %}
            <div class="row">
                <div class="col-md-12">
                    <b>{{ _('Filename') }}:</b>
                    <p style="font-family: monospace; display: inline; margin-left: 10px">
                        {{ new_file.full_display_name }}
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <b>{{ _('Link to file') }}:</b>
                    <div class="input-group" style="padding-bottom: 5px">
                        <input id="file-{{ index }}"
                        class="form-control url-copy-textbox" type="text" value="{{ url_for('file.content', file_id=new_file.id, file_hash=new_file.hash, _external=True) }}" readonly></input>
                        <span class="input-group-btn">
                            <button class="btn btn-primary"
                                title="{{ _('Link copied') }}"
                                id="url-copy-btn-{{ index }}"
                                data-clipboard-target="#file-{{ index }}">
                                <i class="fa fa-clipboard"></i> {{ _('Copy to clipboard') }}
                            </button>
                        </span>
                    </div>
                </div>
            </div>
            {% endfor %}
            </div>
        </div>
        {%- endif -%}
        <div class="panel panel-default">
            <div class="panel-heading">{{ _('Upload file') }}</div>
            <div class="panel-body">
                {{ render_form(form, submit_text=_('Upload')) }}
            </div>
        </div>
{%- endif -%}


<div class="panel panel-default">
    <div class="panel-heading">{{ _('Files') }}</div>
    <div class="panel-body">
        <form class="form" action="{{ url_for('file.list') }}" method="GET">
            <div class="form-group">
                <label>{{ _('Search') }}</label>
                <div class="input-group">
                    <input type="text" class="form-control" name="search" {% if search %}value="{{ search }}"{% endif %}></input><br>
                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-primary">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </div>
            </form>

        <table class="table">
            <thead>
                <tr>
                    <th>{{ _('Filename') }}</th>
                </tr>
            </thead>
            <tbody>
                {% for file in files %}
                    <tr>
                        <td>
                            <a href="{{ url_for('file.content', file_id=file.id, file_hash=file.hash) }}" target="_blank">{{ file.full_display_name }}</a>
                        </td>
                    </tr>
                {% endfor %}
            </ul>
        </table>

        {% if files_paginated %}
        {{ render_pagination(files_paginated, 'file.list') }}
        {% endif %}
    </div>
</div>

{% endblock %}