app/forms/activity.py
from flask_babel import lazy_gettext as _  # gettext
from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from wtforms import StringField, SelectField, TextAreaField, DateTimeField
from wtforms.validators import InputRequired

from app.forms.fields import CustomFormSelectField, EmailField
from app.forms.util import FieldVerticalSplit


class CreateForm(FlaskForm):
    form_id = CustomFormSelectField(_('Form'))
    nl_name = StringField(_('Dutch name'),
                          validators=[InputRequired()])
    nl_description = TextAreaField(_('Dutch description'),
                                   validators=[InputRequired()])
    en_name = StringField(_('English name'),
                          validators=[InputRequired()])
    en_description = TextAreaField(_('English description'),
                                   validators=[InputRequired()])

    names = FieldVerticalSplit([['nl_name', 'nl_description'],
                                ['en_name', 'en_description']])

    start_time = DateTimeField(
        _('Start time'), validators=[
            InputRequired(_('Start time') + " " + _('required'))],
        format='%Y-%m-%d %H:%M')
    end_time = DateTimeField(
        _('End time'), format='%Y-%m-%d %H:%M')

    timerange = FieldVerticalSplit([['start_time'], ['end_time']])

    location = StringField(
        _('Location'), default='Studievereniging VIA, Science Park 904,\
        1098 XH Amsterdam, Nederland')

    price = StringField(_('Displayed price'), default=0)
    picture = FileField(_('Image'))

    # Override validate from the Form class
    def validate(self):

        # Validate all other fields with default validators
        if not FlaskForm.validate(self):
            return False

        # Test if either english or dutch is entered
        if self.start_time.data >= self.end_time.data:
            self.start_time.errors.append(
                _("Start time must be before end time"))
            # Append empty string to mark the field red.
            self.end_time.errors.append('')
            return False

        return True


class ActivityForm(FlaskForm):
    email = EmailField(
        _('E-mail address'), validators=[InputRequired()])
    first_name = StringField(
        _('First name'), validators=[
            InputRequired(_('First name') + " " + _('required'))])
    last_name = StringField(
        _('Last name'), validators=[
            InputRequired(_('Last name') + " " + _('required'))])
    student_id = StringField(
        _('Student ID'), validators=[
            InputRequired(_('Student ID') + " " + _('required'))])
    education_id = SelectField(
        _('Education'), coerce=int)
    introductions = SelectField(_('Number of extra attendants'), coerce=int)

app/views/activity.py
import datetime

from flask import Blueprint
from flask import flash, redirect, render_template, request, url_for, abort, \
    jsonify
from flask_babel import _  # gettext
from flask_login import current_user
from werkzeug.contrib.atom import AtomFeed

# this is now uncommented for breaking activity for some reason
# please some one check out what is happening
import app.utils.google as google
from app import db
from app.decorators import require_role
from app.forms import init_form
from app.forms.activity import ActivityForm, CreateForm
from app.forms.user import SignInForm
from app.models.activity import Activity
from app.models.custom_form import CustomFormResult
from app.models.education import Education
from app.models.mollie import Transaction, TransactionActivity
from app.roles import Roles
from app.service import role_service, file_service
from app.utils import mollie
from app.utils.serialize_sqla import serialize_sqla
from app.enums import FileCategory

blueprint = Blueprint('activity', __name__, url_prefix='/activities')

PICTURE_DIR = 'app/static/activity_pictures/'


# Overview of activities
@blueprint.route('/', methods=['GET', 'POST'])
@blueprint.route('/<string:archive>/', methods=['GET', 'POST'])
@blueprint.route('/list/<int:page_nr>/', methods=['GET', 'POST'])
@blueprint.route('/list/<string:archive>/<int:page_nr>/',
                 methods=['GET', 'POST'])
def view(archive=None, page_nr=1):
    if archive == "archive":
        activities = Activity.query.filter(
            Activity.end_time < datetime.datetime.today()).order_by(
            Activity.start_time.desc())
        title = _('Activity archive') + " - " + _('page') + " " + str(page_nr)
    else:
        activities = Activity.query.filter(
            Activity.end_time > (
                datetime.datetime.now() - datetime.timedelta(hours=12))) \
            .order_by(Activity.start_time.asc())
        title = _('Activities') + ' - ' + _('page') + ' ' + str(page_nr)

    can_write = role_service.user_has_role(current_user,
                                           Roles.ACTIVITY_WRITE)
    return render_template('activity/view.htm',
                           activities=activities.paginate(page_nr, 10, False),
                           archive=archive, title=title, can_write=can_write)


@blueprint.route('/remove/<int:activity_id>/', methods=['POST'])
@require_role(Roles.ACTIVITY_WRITE)
def remove_activity(activity_id=0):
    # Get activity
    activity = Activity.query.filter(Activity.id == activity_id).first()

    # Remove the event from google calendar
    google.delete_activity(activity.google_event_id)

    # Remove it
    db.session.delete(activity)
    db.session.commit()

    return redirect(url_for('activity.view'))


@blueprint.route('/<int:activity_id>/', methods=['GET', 'POST'])
def get_activity(activity_id=0):
    """Activity register and update endpoint.

    Register and update for an activity, with handling of custom forms
    and payment.
    """
    activity = Activity.query.get_or_404(activity_id)

    form = init_form(ActivityForm, obj=current_user)

    # Add education for activity form
    educations = Education.query.all()
    form.education_id.choices = [(e.id, e.name) for e in educations]

    # Set the number of extra attendees
    if activity.form:
        form.introductions.choices = [(0, _('None'))] + [
            (x, "+%d" % x) for x in range(1, activity.form.introductions + 1)]
        form.introductions.default = (0, _('None'))

    auto_open_register_pane = False

    def render(num_extra_attendees=None):
        can_write = role_service.user_has_role(current_user,
                                               Roles.ACTIVITY_WRITE)
        return render_template(
            'activity/view_single.htm', activity=activity, form=form,
            login_form=SignInForm(), title=activity.name,
            auto_open_register=auto_open_register_pane, can_write=can_write,
            num_extra_attendees=num_extra_attendees)

    # Check if there is a custom_form for this activity
    if not activity.form_id:
        # No form, so no registering and handling thereof required.
        return render()

    # You cannot register when you're not a member of via yet.
    if not current_user.has_paid:
        activity.info = _("You have to be a registered member of "
                          "via in order to register for "
                          "activities. If you believe you are a "
                          "member, please contact the board.")
        return render()

    # Check all attendees including extra attendees
    over_max_registrations = activity.form.attendants >= \
        activity.form.max_attendants

    all_form_results = CustomFormResult.query \
        .filter(CustomFormResult.form_id == activity.form_id)

    # Result for the form, may be None if not entered yet.
    form_result = all_form_results \
        .filter(CustomFormResult.owner_id == current_user.id).first()

    # Not filled in, show over limit message or not and let the user register.
    if not form_result:
        if over_max_registrations:
            activity.info = _("The activity has reached its maximum "
                              "number of registrations. You will be "
                              "placed on the reserves list.")
        return render()

    # Set the previous amount of extra attendees
    form.introductions.data = form_result.introductions

    activity.form_data = form_result.data.replace('"', "'")

    auto_open_register_pane = True

    # You're attending if you're on the form results list within the
    # max attendants count.
    is_attending = bool(all_form_results.limit(activity.form.max_attendants)
                        .from_self().filter(
        CustomFormResult.owner_id == current_user.id).first())

    # Payment still required if you're attending, the form says it costs money
    # and you haven't paid yet.
    form_costs_money = form_result.form.price > 0
    payment_required = form_costs_money and is_attending and \
        not form_result.has_paid

    if is_attending:
        introductions = form_result.introductions
    else:
        introductions = None

    if payment_required:
        form.show_pay_button = True
        form.form_result = form_result

    if not payment_required:
        activity.info = \
            _("Your registration has been completed.") + " " + \
            _("You can edit your registration by resubmitting the form.")
    elif is_attending:

        # TODO If paid, make extra attendees read-only

        activity.info = _("You have successfully registered, "
                          "payment is still required!")

        if form_result.form.requires_direct_payment:
            pay_url = url_for('activity.create_mollie_transaction',
                              result_id=form.form_result.id)

            return redirect(pay_url)
    else:
        activity.info = _("The activity has reached its maximum "
                          "number of registrations. You have been "
                          "placed on the reserves list.")

    return render(num_extra_attendees=introductions)


@blueprint.route('/create/', methods=['GET', 'POST'])
@blueprint.route('/edit/<int:activity_id>/', methods=['GET', 'POST'])
@require_role(Roles.ACTIVITY_WRITE)
def create(activity_id=None):
    if activity_id:

        activity = Activity.query.get(activity_id)

        if not activity:
            abort(404)

        title = _("Edit") + " " + str(activity.name)
    else:
        activity = Activity()
        title = _('Create activity')

    form = init_form(CreateForm, obj=activity)

    if request.method == 'POST':

        if form.validate_on_submit():
            form.populate_obj(activity)

            # Facebook ID location, not used yet
            activity.venue = 1

            # Set a custom_form if it actually exists
            form_id = int(form.form_id.data)
            if form_id == 0:
                form_id = None

            activity.form_id = form_id
            activity.owner_id = current_user.id

            if activity.id and activity.google_event_id:
                flash(_('The activity has been edited.'), 'success')

                google.update_activity(activity.google_event_id,
                                       form.nl_name.data,
                                       form.nl_description.data,
                                       form.location.data,
                                       form.start_time.data.isoformat(),
                                       form.end_time.data.isoformat())
            else:
                flash(_('The activity has been created.'), 'success')

                google_activity = google.insert_activity(
                    form.nl_name.data, form.nl_description.data,
                    form.location.data, form.start_time.data.isoformat(),
                    form.end_time.data.isoformat())

                if google_activity:
                    activity.google_event_id = google_activity['id']

            db.session.add(activity)

            file = request.files.get('picture')

            if file and file.filename:
                picture = file_service.add_file(FileCategory.ACTIVITY_PICTURE,
                                                file, file.filename)

                old_picture_id = activity.picture_file_id
                activity.picture_file_id = picture.id

                if old_picture_id:
                    old_picture = file_service.get_file_by_id(old_picture_id)
                    file_service.delete_file(old_picture)

            db.session.commit()

            return redirect(url_for('activity.get_activity',
                                    activity_id=activity.id))

    return render_template('activity/edit.htm', activity=activity, form=form,
                           title=title)


@blueprint.route('/transaction/<int:result_id>/', methods=['GET', 'POST'])

app/views/news.py
from datetime import date, datetime

from flask import Blueprint, abort, render_template, request, flash, \
    redirect, url_for
from flask_babel import _  # gettext
from flask_login import current_user
from sqlalchemy import desc
from werkzeug.contrib.atom import AtomFeed

from app import db
from app.decorators import require_role
from app.forms import init_form
from app.forms.news import NewsForm
from app.models.news import News
from app.roles import Roles
from app.service import role_service

blueprint = Blueprint('news', __name__, url_prefix='/news')


@blueprint.route('/', methods=['GET'])
@blueprint.route('/<int:page_nr>/', methods=['GET'])
def list(page_nr=1):
    items = News.query.filter(News.publish_date <= date.today(),
                              db.or_(News.archive_date >= date.today(),
                                     News.archive_date == None),  # noqa
                              db.or_(current_user.has_paid,
                                     db.not_(News.needs_paid))) \
        .order_by(desc(News.publish_date))

    can_write = role_service.user_has_role(current_user, Roles.NEWS_WRITE)
    return render_template('news/list.htm',
                           items=items.paginate(page_nr, 10, False),
                           archive=False, can_write=can_write)


@blueprint.route('/all/', methods=['GET'])
@blueprint.route('/all/<int:page_nr>/', methods=['GET'])
def all(page_nr=1):
    return render_template('news/list.htm',
                           items=News.query.paginate(page_nr, 10, False),
                           archive=False)


@blueprint.route('/archive/', methods=['GET'])
@blueprint.route('/archive/<int:page_nr>/', methods=['GET'])
def archive(page_nr=1):
    items = News.query.filter(db.and_(News.archive_date < date.today(),
                                      News.archive_date != None))  # noqa

    return render_template('news/list.htm',
                           items=items.paginate(page_nr, 10, False),
                           archive=True)


@blueprint.route('/create/', methods=['GET', 'POST'])
@blueprint.route('/edit/<int:news_id>/', methods=['GET', 'POST'])
@require_role(Roles.NEWS_WRITE)
def edit(news_id=None):
    if news_id:
        news_item = News.query.get_or_404(news_id)
    else:
        news_item = News()

    form = init_form(NewsForm, obj=news_item)

    if form.validate_on_submit():

        # fill the news_item with the form entries.
        form.populate_obj(news_item)

        # Only set writer if post is brand new
        if not news_item.id:
            news_item.user_id = current_user.id

        db.session.add(news_item)
        db.session.commit()

        news_id = news_item.id
        flash(_('News item saved'), 'success')

        return redirect(url_for('news.view', news_id=news_id))

    return render_template('news/edit.htm', form=form, news_id=news_id)


@blueprint.route('/view/', methods=['GET'])
@blueprint.route('/view/<int:news_id>/', methods=['GET'])
def view(news_id=None):
    if not news_id:
        flash(_('This news item does not exist'), 'danger')
        return redirect(url_for('news.list'))

    news = News.query.get_or_404(news_id)
    if not news.can_read():
        return abort(403)

    can_write = role_service.user_has_role(current_user, Roles.NEWS_WRITE)

    return render_template('news/view_single.htm', news=news,
                           can_write=can_write)


@blueprint.route('/delete/', methods=['GET'])
@blueprint.route('/delete/<int:news_id>/', methods=['GET'])
@require_role(Roles.NEWS_WRITE)
def delete(news_id=None):
    if not news_id:
        flash(_('This news item does not exist'), 'danger')
        return redirect(url_for('news.list'))

    news = News.query.get_or_404(news_id)
    db.session.delete(news)
    db.session.commit()

    flash(_('News item succesfully deleted'), 'success')

    return redirect(url_for('news.list'))


@blueprint.route('/rss/', methods=['GET'])
@blueprint.route('/rss/<string:locale>/')
def rss(locale='en'):
    name = 'via nieuws' if locale == 'nl' else 'via news'
    feed = AtomFeed(name, feed_url=request.url, url=request.url_root)
    items = News.query.filter(News.publish_date <= date.today(),
                              db.or_(News.archive_date >= date.today(),
                                     News.archive_date == None),  # noqa
                              db.or_(db.not_(News.needs_paid))) \
        .order_by(News.publish_date.desc()).limit(20)

    for item in items:
        published = datetime.combine(item.publish_date, datetime.min.time())
        title, content = item.get_localized_title_content(locale)
        feed.add(title, content, id=item.id, content_type='markdown',
                 published=published, updated=published,
                 url=url_for('news.view', news_id=item.id),
                 author=item.user.name)

    return feed.get_response()

app/templates/activity/edit.htm
{% from "macros/form.htm" import render_form %}

{% extends "content.htm" %}

{% macro render_before_hook(field) %}
{%- if field.name == 'timerange' -%}
    <div class="alert alert-info">
        <b>{{_('Tip')}}</b>
        {{_('Select a time and date by clicking on the clock')}}
    </div>
{%- endif -%}
{% endmacro %}

{% block content %}

    {% if activity.id %}
        <form method="post" class="pull-right"
            action="{{ url_for('activity.remove_activity', activity_id=activity.id) }}">
            <button class="confirmation btn btn-danger btn-xs" type="submit">
                {{ _("Delete activity") }}
            </button>
        </form>
    {% endif %}

    <h1>{{_('Activity')}}</h1>

    {{ render_form(form, render_before_hook=render_before_hook) }}

{% endblock %}

app/templates/activity/view.htm
{% from "macros/pagination.htm" import render_pagination %}

{% extends "content.htm" %}
{% block content %}
    <div class="btn-group">
        {% if can_write %}
            <a href="/activities/create/"
                class="btn btn-success">{{_('New activity')}}</a>
        {% endif %}

        {% if archive == 'archive' %}
            <a href="{{ url_for('activity.view') }}" class="btn btn-info">
                {{_('Show upcoming activities')}}
            </a>
        {% else %}
            <a href="{{ url_for('activity.view', archive='archive') }}"
                class="btn btn-default">
                {{_('Show activities in the archive')}}
            </a>
            <a href="{{ url_for('activity.rss', locale=get_locale()) }}"
               class="btn btn-default">
                {{_('RSS feed')}}
            </a>
        {% endif %}
    </div>

    <div class="activity">
        {% for activity in activities.items %}

            <a href="{{ url_for('activity.get_activity', activity_id=activity.id)}}">
                <div class="activity-block">
                    <div class="row">
                        <div class="col-md-4 image">
                            <img src="{{ url_for('activity.picture', activity_id=activity.id, picture_type='thumbnail') }}">
                        </div>

                        <div class="col-md-8">
                            <h1>{{activity.name}}</h1>

                            <dl class="time dl-horizontal">
                                <dt><i class="glyphicon glyphicon-home"></i></dt>
                                <dd>{{ activity.location}}</dd>
                                <dt><i class="glyphicon glyphicon-calendar"></i></dt>
                                <dd>{{ activity.get_time() }} </dd>
                                <dd><small>{{ activity.till_now() }}</small></dd>
                            </dl>

                            <h2>
                                {% if activity.price.lower() != "gratis" and activity.price.lower() != "free"
                                        and activity.price != "0" %}
                                    &euro; {{ activity.price}}
                                {% else %}
                                    {{ _('free') }}
                                {% endif %}
                            </h2>

                        </div> {# col-md-8 #}
                        <div class="col-md-8 short_content">
                            {{ activity.get_short_description(600) | markdown }}
                        </div>
                    </div> {# /.row #}
                </div> {# /.activity-blck #}
            </a>
        {% endfor %}
    </div> {# activity #}
    <hr />
    {{ render_pagination(activities, 'activity.view', archive=archive) }}
{% endblock %}

app/templates/activity/view_simple.htm
<a href="/activities">
    <h2>{{_('Activity overview')}}</h2>
</a>
{% for activity in activities.items %}
    <div class="activity">
        <h3>
            <a class="overflow-dots" href="{{ url_for('activity.get_activity', activity_id=activity.id)}}">{{ activity.name }}</a>
        </h3>
        <ul>
            <li class="overflow-dots"><i class="glyphicon glyphicon-calendar"></i>
            {{ activity.get_time() }}</li>

            <li class="overflow-dots"><i class="glyphicon glyphicon-home"></i>
            {{ activity.location }}</li>
        </ul>
        <span>
            {{ activity.till_now() }}
        </span>
    </div>
{% endfor %}

<address>
{{_('Do you have an idea for an activity?')}}<br>
{{_('Send an e-mail to the')}} <a href="mailto:actie@svia.nl">{{_('Activitycommittee')}}</a>.
</address>

app/templates/activity/view_single.htm
{% extends "content.htm" %}

{% from "macros/maps.htm" import render_map %}
{% from "macros/custom_form.htm" import user_fields %}
{% from "macros/form.htm" import render_field, render_field_disabled, render_checkbox, render_submit %}

{% block includes %}
    {% if activity.form_data %}
        <script src={{static_url("/static/js/unserialize.js")}}></script>
        <script>
            $(document).ready(function() {
                $("#custom").unserializeForm("{{ activity.form_data | safe }}");
            });
        </script>
    {% endif %}
    <script src={{static_url("/static/js/custom_form_submission.js")}}></script>
{% endblock %}


{% block content %}
    <div class="page-header">
        {% if can_write %}
            <a href="{{ url_for('activity.create',activity_id=activity.id) }}"
                class="btn btn-warning pull-right">
                <i class="glyphicon glyphicon-pencil"></i>
                {{_('Edit')}}
            </a>
        {% endif %}

        <h1>{{activity.name}}</h1><small> {{ activity.till_now() }}</small>
    </div>

    <div class="accordion" id="acc">
        {% if activity.location %}
        <div class="accordion-group">

            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse"
                    data-parent="#acc" href="#collapseLocation">
                    <i class="glyphicon glyphicon-home"></i>
                    {{_('Location')}}: {{ activity.location}}
                    <span class="pull-right">{{_('Click to expand')}}</span>
                </a>
            </div>

            <div id="collapseLocation" class="accordion-body collapse">
                <div class="accordion-inner">
                    {{ render_map(600, 400, activity.location) }}
                </div>
            </div>
        </div>
        {% endif %}

        {% if activity.form %}
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle{% if not auto_open_register %} collapsed{% endif %}" data-toggle="collapse"
                        data-parent="#acc" href="#collapseForm">
                        <i class="glyphicon glyphicon-star"></i>
                        {{_('Register for this activity')}}
                        <span class="pull-right">{{_('Click to expand')}}</span>
                    </a>
                </div>

                <div id="collapseForm" class="accordion-body collapse{% if auto_open_register %} in{% endif %}">
                    <div class="accordion-inner">
                        {% if current_user.is_authenticated %}
                            <script>
                                var msg_success = '{{ activity.form.msg_success }}';
                            </script>

                            <form id="custom"
                                action="{{ url_for('custom_form.submit', form_id=activity.form.id) }}"
                                enctype="multipart/form-data">
                                {% if activity.form_data %}
                                    <!-- Display custom success message in case user refreshes / forgot info -->
                                    <div class="alert alert-success">
                                        {{ activity.form.msg_success }}
                                    </div>
                                {% endif %}

                                {% if activity.info %}
                                    <div class="alert alert-warning">
                                        {{ activity.info }}
                                    </div>
                                {% endif %}

                                <div class="row">
                                    <div class="col-md-4 col-md-offset-1 pull-right">
                                        {% if form.show_pay_button %}
                                            <a href="{{ url_for('activity.create_mollie_transaction', result_id=form.form_result.id) }}" class="btn btn-warning">
                                                {{_('Pay')}}
                                            </a>
                                        {% endif %}

                                        <h3>{{_('Contact details')}}</h3>
                                        <small>{{_("These details are taken from your account. You can change them on your"
                                            " account page.")}}
                                        </small>
                                        {{ render_field_disabled(form.email) }}
                                        {{ render_field_disabled(form.first_name) }}
                                        {{ render_field_disabled(form.last_name) }}
                                        {{ render_field_disabled(form.student_id) }}
                                        {{ render_field_disabled(form.education_id) }}
                                        <a href="{{ url_for('user.edit_self') }}" class="btn btn-info">
                                            {{_('To account')}}
                                        </a>
                                    </div>
                                    <div class="col-md-7">
                                        <h3>{{_('Please fill in :D')}}</h3>
                                        <p>{{_("Some details like shirt size or diet we try to save, so you don\'t have to fill them in more then once.")}}</p>
                                        {{ activity.form.html | safe }}
                                    </div>
                                </div>
                                <div class="row">
                                    {% if activity.form.terms %}
                                        <div class="col-md-7">
                                            <label>{{_('Terms')}}:</label>
                                            <p>{{ activity.form.terms | markdown }}</p>
                                            <p>{{_('By registering you agree with the terms above.')}}</p>
                                        </div>
                                    {% endif %}
                                    {% if activity.form.introductions > 0 %}
                                        <div class="col-md-7">
                                            {% if num_extra_attendees is defined and num_extra_attendees != None %}
                                                <label>{{_('Number of extra attendants')}}: +{{ num_extra_attendees }}</label>
                                            {% else %}
                                                {{ render_field(form.introductions) }}
                                            {% endif %}
                                        </div>
                                    {% endif %}
                                </div>
                                {% if current_user.has_paid %}
                                    <button id="custom_form" class="btn btn-success">{{_('Send form')}}</button>
                                {% endif %}
                            </form>

                        {% else %}
                            <p>{{_('You must be logged-in to register for an activity.')}}</p>

                            <form method='post' name='sign-in-activity'
                                action='{{ url_for('user.sign_in') }}'>
                                {{ login_form.csrf_token }}
                                {{ render_field(login_form.email) }}
                                {{ render_field(login_form.password) }}
                                {{ render_submit('Inloggen') }}
                            </form>

                            <ul class='list-unstyled'>
                                <li>
                                    <a href='{{ url_for('user.sign_up') }}'>
                                        {{_('Register')}}
                                    </a>
                                </li>
                                <li>
                                    <a href='{{ url_for('user.request_password') }}'>
                                        {{_('Reset password')}}
                                    </a>
                                </li>
                            </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>

    <div class="row">
        <div class="col-md-7 col-xs-12">
            <h4>{{_('Price')}}:
                {% if not activity.price.lower() == "gratis" and not activity.price.lower() == "free"
                        and not activity.price == "0"%}
                    &euro; {{ activity.price }}
                {% else %}
                    {{ _('free') }}
                {% endif %}
            </h4>

            <div class="time">
                <i class="glyphicon glyphicon-calendar"></i>
                {{ activity.get_time() }}
            </div>
        </div>

        <div class="col-md-5 col-xs-12">
            {% if activity.picture_file_id %}
                <a href="{{ url_for('activity.picture', activity_id=activity.id) }}">
                    <img class="img-responsive activity-picture" src="{{ url_for('activity.picture', activity_id=activity.id, picture_type='thumbnail') }}">
                </a>
            {% endif %}
        </div>
    </div>
    <hr>
    <p>{{ activity.description | markdown }}</p>
{% endblock %}