app/models/redirect.py
from app import db
from app.models.base_model import BaseEntity


class Redirect(db.Model, BaseEntity):
    __tablename__ = 'redirect'

    fro = db.Column(db.String(200), unique=True)
    to = db.Column(db.String(200))

    def __init__(self, fro, to):
        self.fro = fro
        self.to = to

app/forms/redirect.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import InputRequired


class RedirectForm(FlaskForm):
    fro = StringField('Van', validators=[InputRequired()])
    to = StringField('Naar', validators=[InputRequired()])

    submit = SubmitField('Opslaan')

app/views/bug.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask import abort, flash, render_template, request
from flask_babel import lazy_gettext as _
from flask_login import current_user

from app.forms.bug import CreateIssueForm
from app.service import gitlab_service
from app.views import redirect_back

blueprint = Blueprint('bug', __name__, url_prefix='/bug')


@blueprint.route('/report/', methods=['GET', 'POST'])
def report():
    if current_user.is_anonymous or not current_user.has_paid:
        abort(403)

    form = CreateIssueForm(request.form)

    if form.validate_on_submit():
        response = gitlab_service.create_gitlab_issue(
            form.summary.data, current_user.email, form.description.data)
        if response:
            flash('The bug has been reported!', 'success')
            return redirect_back()
        else:
            flash(_('Something went wrong.'), 'danger'), 500

    return render_template('bug/report.htm', form=form)

app/views/lang.py
#!/usr/bin/env python
# encoding: utf-8

from flask import Blueprint, redirect, session, url_for, flash
from flask_babel import _
from flask_babel import refresh
from flask_login import current_user

from app import db, constants
from app.views import redirect_back

blueprint = Blueprint('lang', __name__, url_prefix='/lang')


@blueprint.route('/set/<path:lang>', methods=['GET'])
def set_user_lang(lang=None):
    if lang not in constants.LANGUAGES.keys():
        flash(_('Language unsupported on this site') + ': ' + lang, 'warning')
        return redirect(url_for('home.home'))
    if current_user.is_anonymous:
        flash(_('You need to be logged in to set a permanent language.'))
        return redirect_back()

    current_user.locale = lang
    db.session.add(current_user)
    db.session.commit()
    refresh()
    return redirect_back()


@blueprint.route('/<path:lang>', methods=['GET'])
def set_lang(lang=None):
    if lang not in constants.LANGUAGES.keys():
        flash(_('Language unsupported on this site') + ': ' + lang, 'warning')
        return redirect(url_for('home.home'))

    session['lang'] = lang
    if current_user.is_authenticated:
        msg = _("{} is now set as language for this session. To make this "
                "setting permanent, <a href='{}'>click here</a>")
        flash(msg.format(constants.LANGUAGES[lang],
                         url_for('lang.set_user_lang', lang=lang)),
              'safe')

    return redirect_back()

app/views/redirect.py
from flask import Blueprint, render_template, redirect, flash, url_for

from app import db
from app.decorators import require_role
from app.forms import init_form
from app.forms.redirect import RedirectForm
from app.models.redirect import Redirect
from app.roles import Roles

blueprint = Blueprint('redirect', __name__, url_prefix='/redirect')


@blueprint.route('/', methods=['GET', 'POST'])
@blueprint.route('/edit/<int:redirect_id>/', methods=['GET', 'POST'])
@require_role(Roles.REDIRECT_WRITE)
def view(redirect_id=None):
    redirection = Redirect.query.get(redirect_id) if redirect_id else None

    form = init_form(RedirectForm, obj=redirection)

    if form.validate_on_submit():

        fro = form.data['fro'].rstrip('/')
        to = form.data['to']

        old_redirection = Redirect.query.filter(Redirect.fro == fro).first()

        if old_redirection and old_redirection.id != redirect_id:
            flash('Er is al een omleiding vanaf dat pad gedefiniëerd.',
                  'danger')
        else:
            if redirection:
                redirection.fro = fro
                redirection.to = to
            else:
                redirection = Redirect(fro, to)

            db.session.add(redirection)
            db.session.commit()

            flash('De omleiding is succesvol opgeslagen.')

            return redirect(url_for('redirect.view',
                                    redirect_id=redirection.id))

    redirections = Redirect.query.order_by(Redirect.fro).all()

    return render_template('redirect.htm', redirections=redirections,
                           redirection=redirection, form=form)


@blueprint.route('/delete/<int:redirect_id>/', methods=['GET', 'POST'])
@require_role(Roles.REDIRECT_WRITE)
def delete(redirect_id):
    redirection = Redirect.query.get_or_404(redirect_id)

    db.session.delete(redirection)
    db.session.commit()

    flash('De omleiding is succesvol verwijderd.')

    return redirect(url_for('redirect.view'))

app/views/seo.py
from flask import Blueprint, redirect, url_for
from flask import flash, render_template, request
from flask_babel import _  # gettext

from app import db
from app.decorators import require_role
from app.forms import init_form
from app.forms.seo import SeoForm
from app.models.seo import SEO
from app.roles import Roles
from app.utils.seo import get_seo, get_resources

blueprint = Blueprint('seo', __name__, url_prefix='/seo')


@blueprint.route('/edit', methods=['GET', 'POST'])
@blueprint.route('/edit/', methods=['GET', 'POST'])
@require_role(Roles.SEO_WRITE)
def edit_seo():
    module = request.args['module']
    path = request.args['path']

    seo = get_seo(module, path)

    # Retrieve form info.
    form = init_form(SeoForm, obj=seo)

    # On Seo submit (edit or create)
    if form.validate_on_submit():
        if seo:
            # Edit the seo entry
            seo.nl_title = form.nl_title.data.strip()
            seo.en_title = form.en_title.data.strip()
            seo.nl_description = form.nl_description.data.strip()
            seo.en_description = form.en_description.data.strip()
            seo.nl_tags = form.nl_tags.data.strip()
            seo.en_tags = form.en_tags.data.strip()

            db.session.add(seo)
            db.session.commit()
        if not seo:
            # Get seo resources to indentify the seo in the database.
            res = get_resources(module, path)

            # Create the new seo entry
            seo = SEO(res['page'],
                      res['page_id'],
                      res['activity'],
                      res['activity_id'],
                      res['url'],
                      form.nl_title.data.strip(),
                      form.en_title.data.strip(),
                      form.nl_description.data.strip(),
                      form.en_description.data.strip(),
                      form.nl_tags.data.strip(),
                      form.en_tags.data.strip())

            db.session.add(seo)
            db.session.commit()

        flash(_('The seo settings have been saved'), 'success')

        # redirect newly created page
        return redirect(url_for('page.get_page', path=path))

    return render_template('seo/edit.htm', form=form)

app/templates/base.htm
{% from "macros/flash.htm" import render_flash %}

<!DOCTYPE html>
<html>
    <head>
        {% set seo_fields = get_seo_fields(get_locale()) %}

        <title>{{seo_fields.title}}</title>
        <meta description="{{seo_fields.description}}" />
        <meta name="keywords" content="{{seo_fields.tags}}" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <meta property="og:title" content="{{seo_fields.title}}" />
        <meta property="og:description" content="{{seo_fields.description}}" />
        <meta property="og:url" content="{{ request_url }}" />
        <meta property="og:image" content="{{ request_url_root }}static/img/via_facebook_thumbnail.png" />

        <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
        <link rel="mask-icon" href="{{ url_for('static', filename='img/favicon.svg') }}" color="#004b99">
        <link rel="apple-touch-icon" sizes="57x57"   href="{{ url_for('static', filename='img/apple-icon-57x57.png')   }}">
        <link rel="apple-touch-icon" sizes="60x60"   href="{{ url_for('static', filename='img/apple-icon-60x60.png')   }}">
        <link rel="apple-touch-icon" sizes="72x72"   href="{{ url_for('static', filename='img/apple-icon-72x72.png')   }}">
        <link rel="apple-touch-icon" sizes="76x76"   href="{{ url_for('static', filename='img/apple-icon-76x76.png')   }}">
        <link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename='img/apple-icon-114x114.png') }}">
        <link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='img/apple-icon-120x120.png') }}">
        <link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('static', filename='img/apple-icon-144x144.png') }}">
        <link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='img/apple-icon-152x152.png') }}">
        <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/apple-icon-180x180.png') }}">
        <link rel="icon" type="image/png" sizes="192x192" href="{{ url_for('static', filename='img/favicon-192x192.png') }}">
        <link rel="icon" type="image/png" sizes="96x96"   href="{{ url_for('static', filename='img/favicon-96x96.png')   }}">
        <link rel="icon" type="image/png" sizes="32x32"   href="{{ url_for('static', filename='img/favicon-32x32.png')   }}">
        <link rel="icon" type="image/png" sizes="16x16"   href="{{ url_for('static', filename='img/favicon-16x16.png')   }}">
        <link rel="manifest" href="/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="{{ url_for('static', filename='img/ms-icon-144x144.png') }}">
        <meta name="theme-color" content="#004b99">

        <link href="/static/img/via.png" rel="image_src" />
        <link href="{{static_url("/static/styles.css")}}" rel="stylesheet" />

        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-PKHM7J9');</script>

        {% if data is defined %}
            <script>
                window.viaduct = {{json.dumps(serialize_sqla(data))|safe}};
            </script>
        {% else %}
            <script>window.viaduct = {};</script>
        {% endif %}

        <!-- TODO Remove when fully ported to webpack -->
        {% if not vue %}
            <script src="{{static_url("/static/js/global.js")}}"></script>
            <script src="{{static_url("/jsglue.js")}}"></script>
        {% endif %}

        <!-- TODO move to global js -->
        <script>
            window.viaduct.locale = "{{get_locale()}}";
            SentryConfig = {
                dsn: "{{ app_config["SENTRY_DSN_FRONTEND"] }}",
                release: "{{ app_version }}",
                environment: "{{ app_config['ENVIRONMENT'] }}",
            }
        </script>

        {% block includes %}
        {% endblock %}

        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    </head>

    <body>
        {%- if not __fullscreen_mode -%}
        {{ UserAPI.get_membership_warning() | safe }}
        {{ NavigationAPI.get_navigation_bar()|safe }}
        {%- endif -%}
        {% block below_menu %}
        {% endblock %}

        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PKHM7J9"
                          height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

        <div class="container">
            {%- if not __fullscreen_mode -%}
            <p class="text-right guide" style="margin-top: -20px">
                <!-- Language switcher -->
                {% if get_locale() == 'en' %}
                    <a href='{{url_for('lang.set_lang', lang='en')}}' class='btn btn-sm text-muted'><i class="fa fa-language"></i> <u>English</u></a>
                    |
                    <a href='{{url_for('lang.set_lang', lang='nl')}}' class='btn btn-sm'><i class="fa fa-language"></i> Nederlands</a>
                    |
                {% endif %}
                {% if get_locale() == 'nl' %}
                    <a href='{{url_for('lang.set_lang', lang='en')}}' class='btn btn-sm'><i class="fa fa-language"></i> English</a>
                    |
                    <a href='{{url_for('lang.set_lang', lang='nl')}}' class='btn btn-sm text-muted'><i class="fa fa-language"></i> <u>Nederlands</u></a>
                    |
                {% endif %}
                <!-- Guide menu trigger -->
                <a data-icon="glyphicon-picture" class="btn btn-sm" data-toggle="modal" data-target="#moduleGuide">
                    <i class="fa fa-question-circle"></i> Help
                </a>
                |
                {% if can_write_seo %}
                <a href="{{ url_for('seo.edit_seo', module=request.blueprint, path=request.path) }}"  data-icon="glyphicon-search" class="btn btn-sm">
                    <i class="fa fa-search"></i> SEO
                </a>
                |
                {% endif %}
                <a href="{{ url_for('bug.report', next=request.path) }}"  class="btn btn-sm"> <i class="fa fa-bug"></i> Report a bug</a>
                |
                <a href="https://www.facebook.com/groups/studieverenigingvia/" class ="btn btn-sm"> <i class="fa fa-facebook-square"></i> FB groep</a>
                |
                <a href="{{ privacy_policy_url }}" class="btn btn-sm" target="_blank"> <i class="fa fa-book"></i> {{ _('Privacy Policy') }}</a>
            </p>
            {%- endif -%}
            <div class="row">
                <div class="col-sm-12" id="messages">
                    {{ render_flash() }}
                </div>
            </div>

            {% block page %}
            {% endblock %}
            {%- if not __fullscreen_mode -%}
                {% include 'page/get_footer.htm' %}
            {%- endif -%}
        </div>
        <!-- Start guide modal -->
        {% set user_guide = GuideAPI.get_current_user_guide() %}
        {% set admin_guide = GuideAPI.get_current_admin_guide() %}
        <div class="modal fade" id="moduleGuide" tabindex="-1" role="dialog" aria-labelledby="guide" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <b>{{ user_guide.title | markdown }}</b>
              </div>
              <div class="modal-body">
                    {{ user_guide.content | markdown }}
              </div>
              <div class="modal-header">
                <b>{{ admin_guide.title | markdown }}</b>
              </div>
              <div class="modal-body">
                    {{ admin_guide.content | markdown }}
              </div>
            </div>
          </div>
        </div>
        <!-- End guide modal -->
    </body>
    <script src="{{ url_for("static", filename="main.js") }}"></script>
</html>

app/templates/content.htm
{% extends "base.htm" %}

{% block page %}
<div class="row">
    {{ NavigationAPI.get_navigation_menu()|safe }}

    <div class="col-md-10">
        <div class="row">
            <div class="col-md-10" id="navigation_backtrack">
                    {{ NavigationAPI.get_navigation_backtrack()|safe }}
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </div>
</div>
{% endblock %}

app/templates/redirect.htm
{% from 'macros/form.htm' import render_field, render_button %}
{% extends 'content.htm' %}

{% block content %}

<h1>Omleiding</h1>
<p>Creëer omleidingen van URLs, naar URLs.</p>

<h2>{% if redirection %}Bewerk{% else %}Nieuwe{% endif %} omleiding</h2>
<form method='post' class='form-inline'>
    {{ form.csrf_token }}

    {{ render_field(form.fro) }}
    {{ render_field(form.to) }}

    {{ render_button(form.submit, 'btn btn-primary') }}

    {% if redirection %}
        <a href='{{ url_for('redirect.view') }}' class='btn btn-default'>Nieuw</a>
    {% endif %}
</form>

<h2>Bestaande omleidingen</h2>
<table class='table table-condensed'>
    <thead>
        <th>Van</th>
        <th>Naar</th>
        <th>Acties</th>
    </thead>

    <tbody>
        {% for redirection in redirections %}
            <tr>
                <td>{{ redirection.fro }}</td>
                <td>{{ redirection.to }}</td>
                <td>
                    <a href='{{ url_for('redirect.view',
                        redirect_id=redirection.id) }}' class='btn btn-default
                        btn-xs'>
                        <i class='fa fa-edit'></i>
                    </a>
                    <a href='{{ url_for('redirect.delete',
                        redirect_id=redirection.id) }}' class='btn btn-default
                        btn-xs'>
                        <i class='fa fa-trash'></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

app/templates/vue_content.htm
{% extends "base.htm" %}

{% block page %}
    <div id="app"></div>
    <noscript>
        <div class="alert alert-error">{{ _("This page is only available using Javascript. So you better turn it on.") }}</div>
    </noscript>
{% endblock %}

{% block includes %}

{% endblock %}